# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20170504_0427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['id']},
        ),
    ]
