# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20170504_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='region_name',
            new_name='large',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='parent_region',
            new_name='small',
        ),
        migrations.AddField(
            model_name='address',
            name='middle',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
