# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20170504_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(max_length=30)),
                ('cn_name', models.CharField(max_length=50)),
                ('casno', models.CharField(max_length=30, verbose_name='CAS No.')),
                ('hscode', models.CharField(max_length=30, verbose_name='HS CODE')),
                ('chemical_atomic', models.CharField(max_length=50, verbose_name='화학식')),
                ('atomic_amount', models.IntegerField(verbose_name='분자량')),
                ('image', models.ImageField(upload_to='chemical/', verbose_name='구조식')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='companyproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Product'),
        ),
    ]
