# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20170504_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyproduct',
            name='currency',
            field=models.CharField(choices=[('D', 'US$'), ('R', 'RMB')], default='R', max_length=1),
        ),
    ]
