# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20170504_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usage',
            field=models.TextField(blank=True, null=True, verbose_name='용도'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cn_name',
            field=models.CharField(max_length=50, verbose_name='중문이름'),
        ),
        migrations.AlterField(
            model_name='product',
            name='en_name',
            field=models.CharField(max_length=30, verbose_name='영문이름'),
        ),
    ]
