# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20170504_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='appearance1',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='乌洛托品请注明外观'),
        ),
        migrations.AddField(
            model_name='product',
            name='appearance2',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='6-己内酰胺请注明外观'),
        ),
        migrations.AddField(
            model_name='product',
            name='including',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='成分含量'),
        ),
    ]
