# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_salescontract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salescontract',
            name='contract_unitprice',
        ),
        migrations.AddField(
            model_name='salescontract',
            name='unitprice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
