# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auto_20170504_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescontract',
            name='actualshipping_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='실제선적일자'),
        ),
    ]
