# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_salescontract_actualshipping_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescontract',
            name='actualshipping_at',
            field=models.DateField(blank=True, null=True, verbose_name='실제선적일자'),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='contracted_at',
            field=models.DateField(verbose_name='계약일자'),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='shipping_at',
            field=models.DateField(verbose_name='선적일자'),
        ),
    ]
