# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_auto_20170504_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sales_amount', models.IntegerField()),
                ('unitprice', models.FloatField()),
                ('currency', models.CharField(choices=[('D', 'US$'), ('R', 'RMB')], default='R', max_length=1)),
                ('packaging', models.CharField(max_length=100)),
                ('portofdestination', models.CharField(max_length=100, verbose_name='도착항구')),
                ('shipping_at', models.DateField(verbose_name='출발일자')),
                ('actualshipping_at', models.DateField(blank=True, null=True, verbose_name='실제출발일자')),
                ('predictdelivery_at', models.DateField(verbose_name='도착예정일자')),
                ('actualdelivery_at', models.DateField(blank=True, null=True, verbose_name='실제도착일자')),
                ('contracted_at', models.DateField(verbose_name='계약일자')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Product')),
                ('salescontract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.SalesContract')),
            ],
        ),
    ]
