# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_purchasecontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sales_filename', models.CharField(max_length=50, verbose_name='销售合同名字')),
                ('send_sales_contrat', models.BooleanField(default=False, verbose_name='传送销售合同')),
                ('make_purchase_contract', models.BooleanField(default=False, verbose_name='确认购买合同')),
                ('purchase_filename', models.CharField(blank=True, max_length=50, null=True, verbose_name='购买合同名字')),
                ('send_purchase_contrat', models.BooleanField(default=False)),
                ('send_purchase_money', models.BooleanField(default=False, verbose_name='购买付款')),
                ('confirm_packing_marking', models.BooleanField(default=False, verbose_name='传送包装和Marking')),
                ('make_commercial_invoice', models.BooleanField(default=False, verbose_name='做好 Invoice&Packing List')),
                ('commercial_invoice_filename', models.CharField(blank=True, max_length=50, null=True, verbose_name='Invoice 文档名字')),
                ('send_commercial_invoice', models.BooleanField(default=False, verbose_name='传送 Invoice')),
                ('received_warehouse_confirm', models.BooleanField(default=False, verbose_name='从物流公司收到进仓单')),
                ('send_warehouse_confirm_provider', models.BooleanField(default=False, verbose_name='向供应商提供进仓单')),
                ('make_material', models.BooleanField(default=False, verbose_name='准备 非危险品证明书 产品说明书 MSDS')),
                ('not_danger_doc_filename', models.CharField(blank=True, max_length=50, null=True, verbose_name='非危险品证明书文档')),
                ('product_explain_filename', models.CharField(blank=True, max_length=50, null=True, verbose_name='产品说明书文档')),
                ('MSDS_filename', models.CharField(blank=True, max_length=50, null=True, verbose_name='MSDS文档')),
                ('send_MSDS', models.BooleanField(default=False, verbose_name='传送MSDS文档')),
                ('send_material', models.BooleanField(default=False, verbose_name='传送 非危险品证明书 产品说明书 MSDS')),
                ('pallet_cbm', models.CharField(max_length=100, verbose_name='包装后托盘和CBM')),
                ('send_pallet_cbm', models.BooleanField(default=False, verbose_name='传送包装后托盘和CBM信息')),
                ('picture_of_packing1', models.FileField(blank=True, max_length=50, null=True, upload_to='', verbose_name='包装后照片1')),
                ('picture_of_packing2', models.FileField(blank=True, max_length=50, null=True, upload_to='', verbose_name='包装后照片2')),
                ('picture_of_packing3', models.FileField(blank=True, max_length=50, null=True, upload_to='', verbose_name='包装后照片3')),
                ('CoA_filename', models.CharField(blank=True, max_length=50, null=True, verbose_name='CoA')),
                ('send_pictures_CoA', models.BooleanField(default=False, verbose_name='传送照片和CoA')),
                ('send_baoguandan', models.BooleanField(default=False, verbose_name='寄过去报关单')),
                ('send_postcode_number', models.BooleanField(default=False, verbose_name='传送顺丰的号码')),
                ('send_product_name', models.BooleanField(default=False, verbose_name='为了发票传送报关单上的产品名字')),
                ('received_bill_of_lading', models.BooleanField(default=False, verbose_name='从物流公司收到B/L')),
                ('send_bill_of_lading', models.BooleanField(default=False, verbose_name='向客户提供B/L')),
                ('make_FTF_original', models.FileField(blank=True, max_length=50, null=True, upload_to='', verbose_name='原产地证明')),
                ('send_file_for_confirm', models.BooleanField(default=False, verbose_name='为了证明传送文档')),
                ('send_result_file', models.BooleanField(default=False, verbose_name='传送证明书')),
                ('apply_tax_refund', models.DateField(blank=True, null=True, verbose_name='申请退税')),
                ('get_tax_refund', models.DateField(blank=True, null=True, verbose_name='退税日子')),
                ('all_cleared', models.BooleanField(default=False, verbose_name='项目结束')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='purchasecontract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salescontract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allprocess',
            name='sales_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.SalesContract'),
        ),
    ]
