# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_remove_allprocess_send_msds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('T', '贸易'), ('P', '生产'), ('M', '生产&贸易')], default='P', max_length=1, verbose_name='公司种类'),
        ),
        migrations.AlterField(
            model_name='company',
            name='en_name',
            field=models.CharField(max_length=50, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=30, verbose_name='中文名字'),
        ),
        migrations.AlterField(
            model_name='companyproduct',
            name='currency',
            field=models.CharField(choices=[('D', 'USD'), ('R', 'RMB')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='en_name',
            field=models.CharField(max_length=30, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='atomic_amount',
            field=models.FloatField(verbose_name='分子量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cn_name',
            field=models.CharField(max_length=50, verbose_name='中文名字'),
        ),
        migrations.AlterField(
            model_name='product',
            name='en_name',
            field=models.CharField(max_length=30, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='chemical/', verbose_name='结构式'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage',
            field=models.TextField(blank=True, null=True, verbose_name='用途'),
        ),
        migrations.AlterField(
            model_name='purchasecontract',
            name='actualdelivery_at',
            field=models.DateField(blank=True, null=True, verbose_name='实际到达日子'),
        ),
        migrations.AlterField(
            model_name='purchasecontract',
            name='actualshipping_at',
            field=models.DateField(blank=True, null=True, verbose_name='实际出发日子'),
        ),
        migrations.AlterField(
            model_name='purchasecontract',
            name='contracted_at',
            field=models.DateField(verbose_name='合同日子'),
        ),
        migrations.AlterField(
            model_name='purchasecontract',
            name='currency',
            field=models.CharField(choices=[('D', 'USD'), ('R', 'RMB')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='purchasecontract',
            name='portofdestination',
            field=models.CharField(max_length=100, verbose_name='货到的港口'),
        ),
        migrations.AlterField(
            model_name='purchasecontract',
            name='predictdelivery_at',
            field=models.DateField(verbose_name='到达计划日子'),
        ),
        migrations.AlterField(
            model_name='purchasecontract',
            name='shipping_at',
            field=models.DateField(verbose_name='出发计划日子'),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='actualshipping_at',
            field=models.DateField(blank=True, null=True, verbose_name='实际 Shipping 日子'),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='contracted_at',
            field=models.DateField(verbose_name='合同日子'),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='currency',
            field=models.CharField(choices=[('D', 'USD'), ('R', 'RMB')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='devliveryrequest',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='portofdestination',
            field=models.CharField(max_length=100, verbose_name='目的地 港口'),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='portofloading',
            field=models.CharField(max_length=100, verbose_name='Shipping 港口'),
        ),
        migrations.AlterField(
            model_name='salescontract',
            name='shipping_at',
            field=models.DateField(verbose_name='Shipping 计划日子'),
        ),
    ]
